### PR TITLE
document.createElement -> document.createXULElement

### PR DESCRIPTION
**Pull request by jikamens**

### CODE REVIEW

**Comment by Alecaddd** [comment]
Thanks for the PR.
Can you please provide a small description regarding how this PR affects the docs and what issues is solving?
Cheers

**Comment by jikamens** [comment]
Try clicking on the "Files changed" tab.

**Comment by jikamens** [comment]
I mean, really, the last ten commits to master in this project have the commit summary "GitBook: [master] # pages modified", and you're giving me a hard time about my PR description?

**Comment by Alecaddd** [comment]
I'm not giving you a hard time, I simply asked for a small description.
I'm sorry if i didn't do that for previous PRs as I wasn't actively looking at this repo.
I will create a PR template for future contribution, but please don't take my message as a personal attack.

**Comment by jikamens** [comment]
I don't think a PR template is the solution here.

It's a one-commit PR with a six-line change which is fully explicated by the change itself. It's documentation, not code. Changes are by definition self-documented.

If someone takes the time to submit a documentation update, then you can read the freakin' documentation update to find out what it's about, not require that they copy and paste the documentation update into the PR description. That's simply wasting their time.

If people are taking the time to update the documentation, you should meet them half-way. No, actually, you should meet them _more_ than halfway. It's not like people are beating down the doors to do this work. Anyone who wants to chip in should be strongly encouraged and welcomed for doing so, and that means, among other things, not bothering them about trivialities.

**Comment by jobisoft** [comment]
I just got feedback from Jörg, that this change does not affect Thunderbird 68 and thus does not need to be added to the update guide for TB68. It may be even the case, that you break your AddOn for TB68, if you do that change.

**Pull request closed without merging**
