### PR TITLE
First pass at documentation for using bookmarks

### PR DESCRIPTION
**Pull request by PaulMorris**

### CODE REVIEW

**Comment by ryanleesipes** [comment]
@PaulMorris one thing that we should do in the future is make sure the new page are added to summary.md so that they show up in the table of contents.

**Comment by PaulMorris** [comment]
Ah, good call @ryanleesipes.  I'll try to remember that for future pages.

**Comment by jobisoft** [comment]
Thanks, that looks very nice!

May I propose to use `hg refresh` or `hg amend` instead of `hg commit --amend`? It is shorter, and you do not need to append `-m` to specify a commit message, it just takes the one from the parent changeset. I personally like `hg refresh`.

I also would like to introduce `hg wip` (with screenshot) because it helped me a lot to see what i am doing and where I am at:

image

In that screenshoot you can also see, that  c-c comes with a special mark for **comm** which you can use with `hg update` so instead of explaining how to pick a changeset number one can simply update to "comm" which is the latest pulled changeset and create a new bookmark. 

The screenshoot is actually bad, because all my bookmarks are now behind comm, because I just pulled. But before that "comm" was at richards commit and I had three patches moving forward from there. 

What do you think? I can add those changes, if you allow.

**Comment by PaulMorris** [comment]
Thanks @jobisoft !  Feel free to propose improvements and additions.  I'm still learning hg and this was just a first pass, so there's room for improvement.

On `hg amend` or `hg refresh` I like how `hg commit --amend` is the same as `git commit --amend`, so I think it's worth keeping `hg commit --amend` in there.  Mentioning `hg amend` as a shorter form would be good, or alternatively leading with `hg amend` but mentioning that `hg commit --amend` also works if you're used to that from git.  

I like `hg amend` instead of `hg refresh` because it maintains the continuity with git (and it looks like 'refresh' is an alias for 'amend' in hg, so maybe a bit better to stick with primary terms).

`hg wip` looks nice.  That's a new one to me.  (I've been using TortoiseHG for that kind of overview.)  Updating to 'comm' is definitely simpler than looking up the number.  It might be good to still include the number approach, since it's good to know in general.

**Pull request merged**
