### PR TITLE
code change applies as of Apr. 30th also to 60.6.1

### PR DESCRIPTION
**Pull request by opto**
code change applies as of Apr. 29th also to 60.6.1

### CODE REVIEW

**Comment by mkmelin** [comment]
That is not correct. This was bug 1514594 which is unlikely to be backported anywhere.

**Comment by opto** [comment]
you want my code example? It starts working when this is applied, in 60.6.1. (bootstrapped).

If not applied, I cannot set a breakpoint in lines using Gloda (breakpoint is removed automatically), and it seems it calls an exception or similiar.
Just add 
     let igl= Gloda.NOUN_MESSAGE; 
and use ChromeUtils.import(.. as before..); (same for Cu.import etc.)
Debugger shows it to be 102 if the new import is applied. If not, it seems the line is skipped, cannot set breakpoint. Or did I have another error in code?

And I mean as of Apr. 29th, as 30th is tomorrow.

**Comment by opto** [comment]
this search on const {XPCOMUtils}, as an example, 
finds similiar code, so it seems to be in mozilla-esr 60. Is that used for 60.6.1?

https://searchfox.org/mozilla-esr60/search?q=const+%7BXPCOMUtils%7D&path=

If I understand the bug right, one would need to add an , Null in the import to have the old behaviour?

**Comment by mkmelin** [comment]
It finds *similar* code, but not the same code. If it was actually ported to 60, it would be the same syntax. And bug 1504416 would be flagged for backporting. 

I'm not sure what problem you're seeing, but this is not it.

**Comment by opto** [comment]
the search  shows that the new syntax is being applied in Mozilla-esr60, does it not?:
const {XPCOMUtils} = ChromeUtils.import("resource://gre/modules/XPCOMUtils.jsm", {});

That wouldn't be possible without backport? Or would it? Obviously, mozEsr does not do it for Gloda because Gloda isn't in there. 

The old syntax would be 
 ChromeUtils.import("resource://gre/modules/XPCOMUtils.jsm");, 
wouldn't it?

It is just this syntax change I needed in the bootstrapped addon to get access to Gloda. 
The addon does nothing else than adding a menu point and accessing Gloda.NOUN_MESSAGE. It is for test only, no other functionality.

**Comment by mkmelin** [comment]
No, the new syntax is const {XPCOMUtils} = ChromeUtils.import("resource://gre/modules/XPCOMUtils.jsm"); Note there is no scope argument!
(I don't know anything about that particular code, maybe it's just a bug.)

**Comment by opto** [comment]
thanks, I oversaw that.  
I will doublecheck whether I have the Gloda import problem in another TB installation. Yesterday, I had ChromeUtil.import problems also in other addons (XUL) in that TB, after deinstalling, restarting TB, installing, restarting TB. Workflow was: everything working in 60.5, working in 60.6.1, deinstalling, reinstalling, problem with Chromeutils.import on Services.jsm (js? - that is on another PC, I don't remember right now which it is).

Klaus

**Pull request closed without merging**
