### PR TITLE
Explain try server with comm-beta, comm-esrNN

### PR DESCRIPTION
**Pull request by PaulMorris**

### CODE REVIEW

**Comment by darktrojan** [comment]
Thanks, this is probably useful info.

I think it might go better after the section on testing m-c patches, then you can mention that it works because of the `.gecko_rev.yml` file. Probably could also go with a reminder that things might not work the same way on older branches (e.g. `--artifact` only works on central, I should fix that…).

**Comment by Alecaddd** [comment]
@PaulMorris can you update this whenever you have time, like @darktrojan suggested?
I'll merge it after that.

**Comment by PaulMorris** [comment]
Thanks all.  I've incorporated the feedback from @darktrojan and moved this to its own section to make it easier to discover.

**Comment by ryanleesipes** [comment]
LGTM.

**Pull request merged**
