### PR TITLE
Blocking policy

### PR DESCRIPTION
**Pull request by jobisoft**
First step towards rebranding the Firefox version to have something to start with. Inserted todos can be fixed later.

### CODE REVIEW

**Comment by jobisoft** [comment]
The initial commit this PR is based upon is directly taken from here:
https://extensionworkshop.com/documentation/publish/add-ons-blocking-process/

Some formatings did not make it across which have been re-added with this PR as well. Otherwise, it is just replacing `Mozilla` with `Thunderbird Team`. I also update dthe links where it was possible already.

**Comment by jobisoft** [comment]
Approving this PR will not add this to the production version of DTN, but to the branch "add-add-on-policies". Once we have everything set up and running, we can merge that branch into master to make it visible.

**Comment by kewisch** [comment]
This lgtm as an initial version. There are a few changes we'll want to make soon on the Firefox side that we could prepare for:
- soft blocks will no longer be a thing
- plugin blocks are going away, Flash was the last plugin left

**Comment by jobisoft** [comment]
What should happen to the former soft-block criterias?

* They cause severe stability and performance issues in Thunderbird
* They contain non-critical policy violations

Keep the first one, drop the second one, as the second one is covered by "They appear to intentionally violate policy"?

**Pull request closed without merging**
