### PR TITLE
Fix #74 Add a quicker way to access MailExtension API reference

### LINKED ISSUE #74: Add a top-level menu item for MailExtension API
**Step to Reproduce**

0. Open tps://developer.thunderbird.net/
1. Go to Resources and Additional Documentation
2. Click on MailExtension URL in the table (it opens a new tab that goes to https://thunderbird-webextensions.readthedocs.io/en/68/)
3. Click on the "latest version" URL in the note block

**Actual Behavior**

It  takes a lot of clicks to finally get to the MailExtension API documentation. Further, it's not obvious at first that the first link you need to click on to get to the doc is in the "Resources and Additional Documentation" section.

**Expected Behavior**

Having a top-level item in the main menu that send you directly to the API doc would be a good minimal solution. Having the documentation on developer.t.n instead of read the doc would be even better but that could be a separate issue since it'll need more work to migrate the doc.

### PR DESCRIPTION
**Pull request by dannycolin**

### CODE REVIEW

**Comment by jobisoft** [comment]
Thanks for your comment and suggestion. However, I think it breaks the concept, but this is just my impression. New users, who have no idea what MailExt API is, will learn about it directly on the introduction page, there is a link. Experienced users can set a bookmark to the API documentation, if they want to access it directly, no need to go via DTN.

Background: We just reduced the main menu structure because there was too much stuff on the first level, which made navigating very difficult.

**Comment by dannycolin** [comment]
> Experienced users can set a bookmark to the API documentation
> Background: We just reduced the main menu structure because there was too much stuff on the first level, which made navigating very difficult.

The first time I visited the documentation website, even as an experienced user, it wasn't great. Since I already knew about webextension, I didn't think the information would be in "introduction" or in "additional documentation". When I looked at the first one, I completely overlooked the link for the MalExtension API. 

So, maybe a good compromise to avoid undoing your effort to reduce the menu could be to add a more prominent message/link on the introduction page. It could be a box right under the "What are addon?" section saying something like "Already know how it works... go straight to the API reference" or something like that. What do you think?

**Comment by jobisoft** [comment]
I moved the documentation link one position up and removed "additional" to indicate that this link is for the main documentation. I do not want to add an extra link just for the API into the main navigation. Is that ok for you? Any alternative suggestion for the wording of the link names?

**Comment by dannycolin** [comment]
> I moved the documentation link one position up and removed "additional" to indicate that this link is for the main documentation. 

The new wording is perfect. It takes away the confusion added by "additional" where it could be interpreted as optional. I think we can now close the issue.

Thanks a lot :).

**Pull request closed without merging**
